# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e6cdb3e0b4099a9da8009a2868c41d48cb521e15500ee01b6324b8ffc138a1fc12344e12eedea433f25c27f939bcbf46b8b2c99f037bc081c4ca9111552fb31

test:
  secret_key_base: 27152a66d4096fe924bdecf1805c54d52cd3ba0402cb1b5e524b246bfc27081e7b9abed048e0970c4ee59980837db430bb5338641a475ad2ebb8db07b26048e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
